// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvdxwzhajfrhvezxtzxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2ZHh3emhhamZyaHZlenh0enhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTI3NDAsImV4cCI6MjA2NDQyODc0MH0.JczzE0VBkXBjO1zTYmed1xG3kOjJ3XOJNVLxzdoTIm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});